version: "3.5"

services:
  frontend:
    build: "./"
    stdin_open: true
    tty: true
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    env_file:
      - "variables.env"
    volumes:
#      - "./frontend/src:/usr/src/app"
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"


